-- FTask: durable batches of prepared videos delivered to the requesting user in Telegram.
-- This is deliberately separate from the reverted `publications` feature: a batch is file
-- preparation + delivery, not a social-network publication record.

create table if not exists public.delivery_batches (
  id bigint generated by default as identity primary key,
  created_by_tg_id bigint not null,
  account_id bigint references public.track_accounts(id) on delete set null,
  account_label text,
  mode text not null check (mode in ('immediate', 'scheduled')),
  deliver_at timestamptz,
  timezone text not null,
  default_level text not null check (default_level in ('weak', 'medium', 'strong')),
  status text not null default 'preparing' check (status in (
    'preparing', 'ready', 'sending', 'sent', 'failed', 'delivery_unknown', 'cancelled'
  )),
  idempotency_key text not null,
  revision integer not null default 1 check (revision > 0),
  delayed_notified_at timestamptz,
  lease_token text,
  lease_until timestamptz,
  send_started_at timestamptz,
  sent_at timestamptz,
  telegram_chat_id bigint,
  telegram_message_ids bigint[] not null default '{}',
  delivery_attempts integer not null default 0 check (delivery_attempts >= 0),
  error_code text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint delivery_batches_schedule check (
    (mode = 'scheduled' and deliver_at is not null) or
    (mode = 'immediate' and deliver_at is null)
  ),
  constraint delivery_batches_idempotent unique (created_by_tg_id, idempotency_key)
);

create table if not exists public.delivery_batch_items (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.delivery_batches(id) on delete cascade,
  creo_id bigint not null references public.creos(id) on delete restrict,
  -- Values >=100 are reserved for the Edge function's short-lived reorder staging.
  -- The public API still accepts at most ten items and persists final positions 0..9.
  position integer not null check (position >= 0 and position < 1000),
  source_path text not null,
  source_name text,
  uniq_level text not null check (uniq_level in ('weak', 'medium', 'strong')),
  source_revision integer not null default 1 check (source_revision > 0),
  prepared_path text,
  prep_state text not null default 'queued' check (prep_state in ('queued', 'processing', 'ready', 'failed')),
  prep_attempts integer not null default 0 check (prep_attempts >= 0),
  prep_error text,
  prepared_bytes bigint,
  prepared_at timestamptz,
  lease_token text,
  lease_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint delivery_batch_items_position unique (batch_id, position),
  constraint delivery_batch_items_creo unique (batch_id, creo_id)
);

create index if not exists delivery_batches_worker_idx
  on public.delivery_batches (status, deliver_at, created_at)
  where status in ('preparing', 'ready', 'sending');
create index if not exists delivery_batches_owner_idx
  on public.delivery_batches (created_by_tg_id, created_at desc);
create index if not exists delivery_batch_items_worker_idx
  on public.delivery_batch_items (prep_state, lease_until, created_at)
  where prep_state in ('queued', 'processing', 'failed');
create index if not exists delivery_batch_items_batch_idx
  on public.delivery_batch_items (batch_id, position);

create or replace function public.delivery_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists delivery_batches_touch_updated_at on public.delivery_batches;
create trigger delivery_batches_touch_updated_at
before update on public.delivery_batches
for each row execute function public.delivery_touch_updated_at();

drop trigger if exists delivery_batch_items_touch_updated_at on public.delivery_batch_items;
create trigger delivery_batch_items_touch_updated_at
before update on public.delivery_batch_items
for each row execute function public.delivery_touch_updated_at();

alter table public.delivery_batches enable row level security;
alter table public.delivery_batch_items enable row level security;

-- The browser never talks to these tables directly. Telegram initData is checked by the Edge
-- function, which then uses service_role. Keep both public client roles outside the Data API.
revoke all on table public.delivery_batches from anon, authenticated;
revoke all on table public.delivery_batch_items from anon, authenticated;
revoke all on sequence public.delivery_batches_id_seq from anon, authenticated;
revoke all on sequence public.delivery_batch_items_id_seq from anon, authenticated;
grant select, insert, update, delete on table public.delivery_batches to service_role;
grant select, insert, update, delete on table public.delivery_batch_items to service_role;
grant usage, select on sequence public.delivery_batches_id_seq to service_role;
grant usage, select on sequence public.delivery_batch_items_id_seq to service_role;

revoke execute on function public.delivery_touch_updated_at() from public, anon, authenticated;
grant execute on function public.delivery_touch_updated_at() to service_role;

-- Atomic edit/reorder. The Edge function validates ownership, accounts and every Storage path
-- against `creos` first; this RPC only closes the race between item replacement and batch CAS.
create or replace function public.update_delivery_batch(
  p_batch_id bigint,
  p_expected_revision integer,
  p_batch jsonb,
  p_items jsonb
)
returns public.delivery_batches
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_batch public.delivery_batches;
  v_old public.delivery_batch_items;
  v_item jsonb;
begin
  select * into v_batch from public.delivery_batches
    where id = p_batch_id for update;
  if v_batch.id is null or v_batch.revision <> p_expected_revision then
    raise exception 'delivery_conflict' using errcode = '40001';
  end if;
  if v_batch.status in ('sending', 'sent', 'cancelled') then
    raise exception 'delivery_locked' using errcode = '55000';
  end if;

  update public.delivery_batch_items set position = position + 100 where batch_id = p_batch_id;
  delete from public.delivery_batch_items i where i.batch_id = p_batch_id
    and not exists (select 1 from jsonb_array_elements(p_items) x where (x->>'creo_id')::bigint = i.creo_id);

  for v_item in select value from jsonb_array_elements(p_items) loop
    select * into v_old from public.delivery_batch_items
      where batch_id = p_batch_id and creo_id = (v_item->>'creo_id')::bigint;
    if v_old.id is null then
      insert into public.delivery_batch_items(batch_id, creo_id, position, source_path, source_name, uniq_level)
      values (p_batch_id, (v_item->>'creo_id')::bigint, (v_item->>'position')::integer,
              v_item->>'source_path', v_item->>'source_name', v_item->>'uniq_level');
    else
      if v_old.source_path is distinct from (v_item->>'source_path')
         or v_old.uniq_level is distinct from (v_item->>'uniq_level') then
        update public.delivery_batch_items set
          position = (v_item->>'position')::integer,
          source_path = v_item->>'source_path', source_name = v_item->>'source_name',
          uniq_level = v_item->>'uniq_level', source_revision = source_revision + 1,
          prepared_path = null, prep_state = 'queued', prep_attempts = 0, prep_error = null,
          prepared_bytes = null, prepared_at = null, lease_token = null, lease_until = null
        where id = v_old.id;
      else
        update public.delivery_batch_items set position = (v_item->>'position')::integer,
          source_name = v_item->>'source_name' where id = v_old.id;
      end if;
    end if;
  end loop;

  update public.delivery_batches set
    account_id = nullif(p_batch->>'account_id', '')::bigint,
    account_label = nullif(p_batch->>'account_label', ''),
    mode = p_batch->>'mode',
    deliver_at = nullif(p_batch->>'deliver_at', '')::timestamptz,
    timezone = p_batch->>'timezone',
    default_level = p_batch->>'default_level',
    revision = revision + 1,
    status = case
      when exists (
        select 1 from public.delivery_batch_items
        where batch_id = p_batch_id and prep_state = 'failed'
      ) then 'failed'
      when exists (
        select 1 from public.delivery_batch_items
        where batch_id = p_batch_id and (prep_state <> 'ready' or prepared_path is null)
      ) then 'preparing'
      else 'ready'
    end,
    error_code = null, error_message = null, lease_token = null, lease_until = null
  where id = p_batch_id returning * into v_batch;
  return v_batch;
end;
$$;

revoke execute on function public.update_delivery_batch(bigint, integer, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.update_delivery_batch(bigint, integer, jsonb, jsonb) to service_role;
