-- FTask: учёт публикаций по аккаунтам + планирование + подготовка версий (2026-09-17).
-- Публикация = конкретный исходный ассет крео × конкретный аккаунт × дата, со своими
-- настройками обработки, подготовленным/финальным файлом и ТРЕМЯ независимыми статусами
-- (обработка / доставка / публикация). Реестр аккаунтов — существующий track_accounts (расширяем).
-- Идемпотентно; ничего не удаляет и не переименовывает. Старый фронт/Edge продолжают работать.

-- ---------------------------------------------------------------- track_accounts: план-настройки
-- (channel_id/archived_at уже добавлены воронкой v2). Здесь — часовой пояс и пресет обработки.
alter table public.track_accounts
  add column if not exists timezone           text,
  add column if not exists default_uniq_level text;

alter table public.track_accounts drop constraint if exists track_accounts_default_uniq_check;
alter table public.track_accounts add constraint track_accounts_default_uniq_check
  check (default_uniq_level is null or default_uniq_level in ('none','weak','medium','strong'));

-- ---------------------------------------------------------------- публикации
create table if not exists public.publications (
  id                 bigint generated by default as identity primary key,
  creo_id            bigint not null references public.creos (id) on delete cascade,
  -- nullable: легаси-отметки (creos.posters[]) переносятся как «аккаунт не указан»
  account_id         bigint references public.track_accounts (id),

  -- какой именно исходный ассет карточки выбран (у карточки бывает несколько готовых видео)
  source_kind        text    not null default 'result' check (source_kind in ('source','result')),
  source_index       int     not null default 0,
  source_path        text,                                    -- снимок пути в Storage на момент плана

  -- планирование
  planned_at         timestamptz,
  tz                 text,                                    -- пояс, в котором введено время

  -- обработка: снимок настроек, зафиксированный при сохранении (приоритет над пресетом аккаунта)
  uniq_level         text    check (uniq_level in ('none','weak','medium','strong')),
  process_flip       boolean not null default false,
  process_settings   jsonb   not null default '{}'::jsonb,

  -- подготовленная обработчиком версия
  prepared_path      text,
  prepared_state     text    not null default 'queue'
                       check (prepared_state in ('queue','processing','ready','failed','skip')),
  prepared_error     text,
  prepared_attempts  int     not null default 0,
  prepared_at        timestamptz,
  prepared_version   int     not null default 0,             -- растёт на «создать новую версию»

  -- ручная доработка в Edits (субтитры/музыка) — отдельно от подготовленной
  needs_edits        boolean not null default false,
  edits_note         text,
  final_path         text,                                   -- финальный файл после монтажа
  final_by_tg_id     bigint,
  final_at           timestamptz,

  -- контент
  caption            text,
  note               text,

  -- доставка файла в Telegram
  delivery_mode      text    not null default 'on_ready'
                       check (delivery_mode in ('on_ready','before_time','morning')),
  delivery_lead_min  int,                                    -- за сколько минут до planned_at (before_time)
  delivery_state     text    not null default 'pending'
                       check (delivery_state in ('pending','sent','failed','unknown')),
  delivered_at       timestamptz,
  delivery_chat_id   bigint,
  delivery_msg_id    bigint,
  delivery_file_id   text,                                   -- tg file_id (повторная выдача без перезаливки)

  -- публикация (ручная; наступление времени и отправка файла НЕ означают публикацию)
  publish_state      text    not null default 'planned'
                       check (publish_state in ('planned','awaiting_confirm','published','cancelled')),
  published_at       timestamptz,
  reel_url           text,
  confirmed_by_tg_id bigint,

  -- служебное
  reminder_count     int     not null default 0,
  created_by_tg_id   bigint,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  state_version      int     not null default 0              -- CAS для callbacks/конкурентных правок
);

-- Выборки бота/аппы (частичные — крошечные):
create index if not exists publications_prep_pending_idx
  on public.publications (created_at)
  where prepared_state in ('queue','failed');
create index if not exists publications_delivery_pending_idx
  on public.publications (planned_at)
  where delivery_state = 'pending';
create index if not exists publications_publish_open_idx
  on public.publications (planned_at)
  where publish_state in ('planned','awaiting_confirm');
create index if not exists publications_account_planned_idx
  on public.publications (account_id, planned_at);
create index if not exists publications_creo_idx
  on public.publications (creo_id);

-- updated_at при любой правке
create or replace function public.publications_touch_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
drop trigger if exists publications_touch_updated_at on public.publications;
create trigger publications_touch_updated_at
  before update on public.publications
  for each row execute function public.publications_touch_updated_at();

-- RLS (весь доступ через service_role; политики не нужны, как у остальных таблиц проекта)
alter table public.publications enable row level security;
