-- FTask: единый каталог (2026-09-13).
-- Добавляет: исходники референсов в Storage (готовит бот), ниши (общие, много-ко-многим),
-- отложение (командное, отдельно от archived_at), заметки к крео.
-- Идемпотентно: можно применять повторно. Не удаляет и не переименовывает существующее.
-- Старый фронт/Edge v13 продолжают работать: новые колонки nullable/с дефолтами.

-- ---------------------------------------------------------------- creos: исходники
alter table public.creos
  add column if not exists source_paths        jsonb        not null default '[]'::jsonb,
  add column if not exists source_poster       text,
  add column if not exists source_clip         text,
  -- null = ещё не готовили; ready | none (нечего готовить: text/ссылка без скачанного)
  -- | too_big (Bot API getFile > 20 МБ) | failed (ошибка, см. source_error; бот повторит)
  add column if not exists source_state        text,
  add column if not exists source_error        text,
  add column if not exists source_attempts     integer      not null default 0,
  add column if not exists source_prepared_at  timestamptz;

alter table public.creos drop constraint if exists creos_source_state_check;
alter table public.creos add constraint creos_source_state_check
  check (source_state is null or source_state in ('ready','none','too_big','failed'));

-- индекс под выборку бота: «что ещё не подготовлено» (частичный, крошечный)
create index if not exists creos_source_pending_idx
  on public.creos (created_at)
  where source_state is null or source_state = 'failed';

-- ---------------------------------------------------------------- creos: отложение + заметки
alter table public.creos
  add column if not exists deferred_at         timestamptz,
  add column if not exists deferred_by_tg_id   bigint,
  add column if not exists notes               text,
  add column if not exists notes_updated_at    timestamptz,
  add column if not exists notes_by_tg_id      bigint;

-- ---------------------------------------------------------------- ниши
create table if not exists public.niches (
  id               bigint generated by default as identity primary key,
  name             text        not null,
  -- ключ уникальности: без регистра и краевых пробелов («Косплей» = «косплей » — одно и то же)
  name_key         text        generated always as (lower(btrim(name))) stored,
  created_by_tg_id bigint,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint niches_name_not_blank check (btrim(name) <> ''),
  constraint niches_name_len check (char_length(name) <= 60)
);
create unique index if not exists niches_name_key_uidx on public.niches (name_key);

create table if not exists public.creo_niches (
  creo_id   bigint not null references public.creos (id) on delete cascade,
  niche_id  bigint not null references public.niches (id) on delete cascade,
  added_by_tg_id bigint,
  added_at  timestamptz not null default now(),
  primary key (creo_id, niche_id)
);
create index if not exists creo_niches_niche_idx on public.creo_niches (niche_id);

-- В проекте есть event-триггер rls_auto_enable(): RLS на новые таблицы включится сам.
-- На случай его отсутствия — явно (весь доступ через service_role, политики не нужны).
alter table public.niches      enable row level security;
alter table public.creo_niches enable row level security;

-- Атомарная замена набора ниш у крео (одна транзакция; конкурентные вызовы не оставляют
-- «полусостояния» — последний победивший набор целиком).
create or replace function public.set_creo_niches(p_creo_id bigint, p_niche_ids bigint[], p_by bigint default null)
returns bigint[]
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ids bigint[];
begin
  -- только существующие ниши, без дублей
  select coalesce(array_agg(distinct n.id order by n.id), '{}')
    into v_ids
    from unnest(coalesce(p_niche_ids, '{}')) as u(id)
    join public.niches n on n.id = u.id;
  delete from public.creo_niches where creo_id = p_creo_id and not (niche_id = any (v_ids));
  insert into public.creo_niches (creo_id, niche_id, added_by_tg_id)
    select p_creo_id, x, p_by from unnest(v_ids) as x
    on conflict do nothing;
  return v_ids;
end;
$$;
revoke all on function public.set_creo_niches(bigint, bigint[], bigint) from public, anon, authenticated;
grant execute on function public.set_creo_niches(bigint, bigint[], bigint) to service_role;

-- updated_at ниши при переименовании
create or replace function public.niches_touch_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
drop trigger if exists niches_touch_updated_at on public.niches;
create trigger niches_touch_updated_at
  before update on public.niches
  for each row execute function public.niches_touch_updated_at();
